# Generated by Django 6.0 on 2026-01-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
